### ISSUE TITLE
Wiring instructions & part list for wakeup light

### ISSUE THREAD

**Issue by wakeup-light** [PaesslerAG/maker-monday#1]
Is it possible to publish some wiring instructions for the wakeup light including a part list. Adding one or two fritzing style pictures would also be quite nice.

By the way who is the guy on the right with zero knowledge?

**Comment by bhupfer** [comment]
We are using some standard WS2812B LEDs. You can get them in different shapes and sizes. Just Google them you will find a lot!

The wiring is straight forward. Just connect the Voltage and Ground to the specific ports of your device. For the Ledunia you can check the PinOut here: http://ledunia.de/index.php/2017-07-24-21-18-46/start

Connect the Single Data Pin to one GPIO and set the GPIO ID within your code. Check the PinOut of your device here too.
