### ISSUE TITLE
compile error Smart Mailbox

### ISSUE THREAD

**Issue by martz170** [PaesslerAG/maker-monday#7]
Hi, 
thanks for this cool Smart-Mailbox project, but i constantly get an compilation error:

Compilation error: 'GPIO_SEL_25' was not declared in this scope; did you mean 'GPIO_NUM_25'?

I tried to rename, but no success.
All Libs are present and Board Support URL is also ok.

Using Arduino 2.3.2 / Firebeetle ESP 32 E

Any Ideas ?

Thanks

**Comment by McSlow** [comment]
Hi,
the code is pretty old and it seems the bitselectors for getting the wakeup reason are no more defined.
Instead, there's now a function for getting the pin like there is one for getting the wakeup reason, called `esp_sleep_get_ext1_wakeup_status()` 

If you give me a day or two, i'll find out how.

**Comment by martz170** [comment]
Hi McSlow,

that would be awsome ! 

Cheers
